#!/usr/bin/env bash
# build_app.sh — assemble a minimal macOS .app bundle that launches the
# media-catalog Streamlit UI on double-click.
#
# Re-run after moving the project: the bundle hard-codes the project path.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="media-catalog"
APP_DIR="${APP_DIR:-$HOME/Applications}"
APP_PATH="$APP_DIR/${APP_NAME}.app"
VERSION="0.1.0"

# Resolve a streamlit binary: prefer a project-local venv (self-contained),
# else fall back to whatever `streamlit` is on PATH (e.g. miniconda). The app
# only depends on streamlit — everything else is Python's standard library.
resolve_streamlit() {
    for v in "$PROJECT_DIR/.venv" "$PROJECT_DIR/venv"; do
        [[ -x "$v/bin/streamlit" ]] && { echo "$v/bin/streamlit"; return; }
    done
    command -v streamlit 2>/dev/null || true
}
STREAMLIT="$(resolve_streamlit)"
if [[ -z "$STREAMLIT" ]]; then
    echo "error: no streamlit found (no project venv, none on PATH)." >&2
    echo "       fix: python3 -m venv $PROJECT_DIR/.venv && \\" >&2
    echo "            $PROJECT_DIR/.venv/bin/pip install -r $PROJECT_DIR/requirements.txt" >&2
    exit 1
fi
if [[ ! -f "$PROJECT_DIR/app.py" ]]; then
    echo "error: $PROJECT_DIR/app.py not found." >&2
    exit 1
fi
echo "  streamlit: $STREAMLIT"

mkdir -p "$APP_DIR"
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# ----- icon -----
# If assets/icon.png exists, build a multi-resolution .icns from it.
# Otherwise the .app uses the macOS default generic icon.
ICON_SRC="$PROJECT_DIR/assets/icon.png"
ICON_NAME=""
if [[ -f "$ICON_SRC" ]]; then
    echo "  building icns from $ICON_SRC..."
    ICONSET_DIR="$(mktemp -d)/AppIcon.iconset"
    mkdir -p "$ICONSET_DIR"
    declare -a SIZES=(16 32 64 128 256 512 1024)
    for s in "${SIZES[@]}"; do
        sips -z "$s" "$s" "$ICON_SRC" --out \
             "$ICONSET_DIR/icon_${s}x${s}.png" > /dev/null
        if [[ "$s" != "1024" ]]; then
            dbl=$((s * 2))
            sips -z "$dbl" "$dbl" "$ICON_SRC" --out \
                 "$ICONSET_DIR/icon_${s}x${s}@2x.png" > /dev/null
        fi
    done
    iconutil -c icns "$ICONSET_DIR" -o \
             "$APP_PATH/Contents/Resources/AppIcon.icns"
    rm -rf "$(dirname "$ICONSET_DIR")"
    ICON_NAME="AppIcon"
fi

# ----- Info.plist -----
cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>           <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>           <string>com.rleite.${APP_NAME}</string>
    <key>CFBundleName</key>                 <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>          <string>media-catalog</string>
    <key>CFBundlePackageType</key>          <string>APPL</string>
    <key>CFBundleVersion</key>              <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key>   <string>${VERSION}</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
$([ -n "$ICON_NAME" ] && echo "    <key>CFBundleIconFile</key>            <string>$ICON_NAME</string>")
    <key>LSMinimumSystemVersion</key>       <string>11.0</string>
    <key>LSUIElement</key>                  <false/>
    <key>NSHighResolutionCapable</key>      <true/>
    <key>NSPrincipalClass</key>             <string>NSApplication</string>
</dict>
</plist>
PLIST

# ----- launcher script -----
LAUNCHER="$APP_PATH/Contents/MacOS/${APP_NAME}"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# media-catalog launcher — double-click entry point.
# Auto-generated by build_app.sh on $(date '+%Y-%m-%dT%H:%M:%S').

PROJECT="$PROJECT_DIR"
APP_PY="\$PROJECT/app.py"
LOG_DIR="\$HOME/Library/Logs"
LOG="\$LOG_DIR/media-catalog.log"
PORT="\${MEDIA_CATALOG_PORT:-8503}"

# Re-resolve streamlit at launch time (venv may have been added since build).
STREAMLIT=""
for v in "\$PROJECT/.venv" "\$PROJECT/venv"; do
    [[ -x "\$v/bin/streamlit" ]] && { STREAMLIT="\$v/bin/streamlit"; break; }
done
[[ -z "\$STREAMLIT" ]] && STREAMLIT="\$(command -v streamlit 2>/dev/null || true)"
# baked-in fallback from build time
[[ -z "\$STREAMLIT" ]] && STREAMLIT="$STREAMLIT"

mkdir -p "\$LOG_DIR"
{
    echo
    echo "===== media-catalog starting at \$(date) ====="
    echo "  project:   \$PROJECT"
    echo "  streamlit: \$STREAMLIT"
} >> "\$LOG"

err_dialog() {
    /usr/bin/osascript -e "display dialog \"\$1\" buttons {\"OK\"} default button \"OK\" with icon stop with title \"media-catalog\"" \\
        >> "\$LOG" 2>&1 || true
}

if [[ ! -x "\$STREAMLIT" && -z "\$(command -v "\$STREAMLIT" 2>/dev/null)" ]]; then
    err_dialog "streamlit not found — install it or create a venv, then re-run build_app.sh."
    exit 1
fi
if [[ ! -f "\$APP_PY" ]]; then
    err_dialog "app.py not found at \$APP_PY — re-run build_app.sh."
    exit 1
fi

# Find a free port if 8503 (or \$MEDIA_CATALOG_PORT) is busy, so it can coexist
# with drive-xray (8501) and other instances.
port_free() {
    ! /usr/sbin/lsof -i ":\$1" -sTCP:LISTEN > /dev/null 2>&1
}
for offset in 0 1 2 3 4 5 6 7 8 9; do
    CANDIDATE=\$((PORT + offset))
    if port_free "\$CANDIDATE"; then
        PORT="\$CANDIDATE"
        break
    fi
done
echo "  port:      \$PORT" >> "\$LOG"

# Streamlit opens the browser itself.
exec "\$STREAMLIT" run "\$APP_PY" \\
    --server.port "\$PORT" \\
    --server.headless false \\
    --browser.gatherUsageStats false \\
    >> "\$LOG" 2>&1
LAUNCH
chmod +x "$LAUNCHER"

# Touch the bundle so Launch Services picks it up.
/usr/bin/touch "$APP_PATH"

cat <<DONE

✅ Built ${APP_NAME}.app

  Bundle:   $APP_PATH
  Logs:     ~/Library/Logs/media-catalog.log
  Launcher: $LAUNCHER
  Port:     8503 (auto-bumps if busy; override with MEDIA_CATALOG_PORT)

How to use:
  • Double-click the app in Finder → ~/Applications/${APP_NAME}.app
  • Or run from terminal:  open "$APP_PATH"
  • Drag it to the Dock for a permanent button.

Tip: drop a square PNG at assets/icon.png and re-run this script for a custom icon.
DONE
